# Generated by Django 5.1.2 on 2024-10-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hello',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
