# Generated by Django 5.1.2 on 2024-10-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_customuser_first_name_remove_customuser_hello_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
    ]
