# Generated by Django 5.1.2 on 2024-10-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='static/myapp/img/default_user.png', upload_to=''),
        ),
    ]
